<a href="https://colab.research.google.com/github/KolaSusmitha/AI-Engineer-Journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                **DAY1**

In [1]:
#CREATE ARRAY

import numpy as np

a = np.array([1, 2, 3, 4])

print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
#MATRIX

import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
#SHAPE
print(matrix.shape)

(2, 3)


In [4]:
#ADDITION
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [5]:
#MULTIPLICATION
print(a*b)

[ 4 10 18]


In [6]:
#DOT PRODUCT
print(np.dot(a,b))

32


In [7]:
#STATISTICS
data = np.array([10,20,30,40,50])

print(np.mean(data))
print(np.std(data))
print(np.max(data))
print(np.min(data))

30.0
14.142135623730951
50
10


#Assignment
1.Create an array of 10 numbers.
Find mean. Find maximum.

2.Create:

[
 [2,4,6],
 [8,10,12]
]

Find:

Shape,
Mean,
Maximum value

3.Create two vectors:

[3,4,5]

and

[6,7,8]

Calculate:

Addition
Multiplication
Dot Product

In [13]:
#1
import numpy as np
roll=np.array([1,2,3,4,5])
print(roll)
print(np.mean(roll))
print(np.max(roll))

[1 2 3 4 5]
3.0
5


In [16]:
#2
a=np.array([[2,4,6],[8,10,12]])
print(a)
print(a.shape)
print(np.mean(a))
print(np.max(a))

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
7.0
12


In [20]:
#3
b=np.array([3,4,5])
c=np.array([6,7,8])
print(b+c)
print(b*c)
print(np.dot(b,c))

[ 9 11 13]
[18 28 40]
86
