<a href="https://colab.research.google.com/github/KolaSusmitha/AI-Engineer-Journey/blob/main/Day-02/Day_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#INDEXING
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[1:5])

[20 30 40 50]


In [2]:
#NEGATIVE INDEXING
print(arr[-1])

50


In [3]:
#SLICING
arr = np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [8]:
#MATRIX SLICING
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [5]:
#to get first column
print(matrix[:,0])

[1 4 7]


In [6]:
#BROADCASTING
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [10]:
#VECTORIZATION
arr = np.array([1,2,3,4,5])
result = arr * 2
print(result)

[ 2  4  6  8 10]


#Assignment

1.Create:

np.array([5,10,15,20,25])

Print:
First element,
Last element,
Middle element


2.Create:

[
 [10,20,30],
 [40,50,60],
 [70,80,90]
]

Print:

First row,
Second column



3.Create:

np.array([1,2,3,4,5])

Use vectorization to:

Add 100,
Multiply by 10,
Divide by 2

No loops allowed.

In [12]:
#1
a=np.array([5,10,15,20,25])
print(a[0])
print(a[-1])
print(a[-3])

5
25
15


In [14]:
#2
a=np.matrix([[10,20,30],[40,50,60],[70,80,90]])

print(a[0])
print(a[:,-2])

[[10 20 30]]
[[20]
 [50]
 [80]]


In [15]:
#3
a=np.array([1,2,3,4,5])
print(a+100)
print(a*10)
print(a/2)

[101 102 103 104 105]
[10 20 30 40 50]
[0.5 1.  1.5 2.  2.5]
